version: '2.0'
services:

  mqtt:
    image: eclipse-mosquitto:1.4.12
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data:rw
      #- ./mosquitto/log:/mosquitto/log


  movie-service:
      build: ./movie-service
      container_name: movie-service
      environment:
        API_PORT: 8082
        JWT_SECRET: myfancysecret
        MQTT_URL: mqtt://mosquitto:1883
      depends_on:
        - mqtt
