version: '2.1'
services:

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    env_file:
      - ./config.env

  movie-service:
    build: ./movie-service
    container_name: movie-service
    network_mode: "host"
    env_file:
      - ./config.env

  api-service:
    build: ./api-service
    container_name: api-service
    network_mode: "host"
    ports:
      - 3030:3030
    env_file:
      - ./config.env
    environment:
      API_PORT: 8082
